#!/bin/bash
# auto_deploy_best.sh - Automatically benchmark, select winner, and deploy

set -e

echo "========================================="
echo "Gonka MLNode - Auto Deploy Best Config"
echo "========================================="

# Source environment
source /data/gonka-scripts/setup_env.sh

# Step 1: Run benchmarks on all configs
echo "[1/5] Running benchmarks on TP=2, TP=4, TP=8..."
bash /data/gonka-scripts/gonka_benchmark_complete.sh

# Step 2: Query SQLite for best result
echo "[2/5] Analyzing benchmark results..."
BEST_RESULT=$(sqlite3 /data/gonka-scripts/compressa-perf-db.sqlite << EOF
SELECT experiment_name, 
       json_extract(value, '$.THROUGHPUT_OUTPUT_TOKENS') as throughput
FROM experiment_results 
WHERE metric = 'summary'
  AND experiment_name LIKE 'gonka-tp%'
ORDER BY throughput DESC 
LIMIT 1;
EOF
)

BEST_CONFIG=$(echo "$BEST_RESULT" | cut -d'|' -f1)
BEST_THROUGHPUT=$(echo "$BEST_RESULT" | cut -d'|' -f2)

# Extract TP value from experiment name (e.g., "gonka-tp4-official" -> 4)
TP_VALUE=$(echo "$BEST_CONFIG" | sed 's/.*tp\([0-9]*\).*/\1/')

echo ""
echo "✓ Best configuration found: TP=$TP_VALUE"
echo "✓ Throughput: $BEST_THROUGHPUT tok/s"
echo ""

# Step 3: Generate production startup script dynamically
echo "[3/5] Generating production startup script..."

cat > /data/gonka-scripts/start_production_auto.sh << 'EOFSCRIPT'
#!/bin/bash
# Auto-generated production script - DO NOT EDIT MANUALLY
# Generated by auto_deploy_best.sh

set -e

# Configuration from benchmark winner
TP_SIZE=__TP_VALUE__
PP_SIZE=1

# Environment setup
export VLLM_USE_V1=0
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_SOCKET_IFNAME=eth0
export HF_HOME=/data/.cache/huggingface
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

source /data/gonka-scripts/setup_env.sh

# Display configuration
echo "========================================="
echo "MLNode Configuration"
echo "========================================="
echo "MLNode Public IP: $MLNODE_IP"
echo "Inference Port: $MLNODE_INFERENCE_PORT"
echo "Management Port: $MLNODE_MANAGEMENT_PORT"
echo ""
echo "Network Node: $NETWORK_NODE_IP"
echo "Network Node Admin API: $NETWORK_NODE_ADMIN_API"
echo "PoC Callback URL: $POC_CALLBACK_URL"
echo "========================================="

echo "[$(date +'%a %b %e %H:%M:%S %Z %Y')] Starting Gonka MLNode - Production"
echo "[$(date +'%a %b %e %H:%M:%S %Z %Y')] MLNode Public IP: $MLNODE_IP"
echo "[$(date +'%a %b %e %H:%M:%S %Z %Y')] Network Node: $NETWORK_NODE_IP"
echo "[$(date +'%a %b %e %H:%M:%S %Z %Y')] Configuration: TP=$TP_SIZE (AUTO-SELECTED WINNER)"
echo "[$(date +'%a %b %e %H:%M:%S %Z %Y')] Inference Port: $MLNODE_INFERENCE_PORT"

# Kill existing processes
echo "[$(date +'%a %b %e %H:%M:%S %Z %Y')] Killing existing vLLM processes..."
pkill -9 -f "vllm" || true
sleep 2
pkill -9 -f "python3.*vllm" || true
sleep 8

# Start vLLM
echo "[$(date +'%a %b %e %H:%M:%S %Z %Y')] Starting vLLM with TP=$TP_SIZE..."

vllm serve "$MODEL_NAME" \
    --host 0.0.0.0 \
    --port $MLNODE_INFERENCE_PORT \
    --trust-remote-code \
    --max-model-len 16384 \
    --tensor-parallel-size $TP_SIZE \
    --pipeline-parallel-size $PP_SIZE \
    --max-num-batched-tokens 32768 \
    --max-num-seqs 256 \
    2>&1 | tee -a /data/logs/production_auto.log
EOFSCRIPT

# Replace TP_VALUE in the script
sed -i "s/__TP_VALUE__/$TP_VALUE/g" /data/gonka-scripts/start_production_auto.sh
chmod +x /data/gonka-scripts/start_production_auto.sh

echo "✓ Production script generated with TP=$TP_VALUE"

# Step 4: Start production in screen
echo "[4/5] Starting production deployment..."
screen -dmS mlnode-prod bash /data/gonka-scripts/start_production_auto.sh

# Wait for startup
echo "Waiting for vLLM to start (this takes 3-5 minutes)..."
sleep 180  # Wait 3 minutes

# Check if it started
MAX_WAIT=300  # 5 more minutes max
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
    if curl -s http://localhost:5000/health > /dev/null 2>&1; then
        echo "✓ vLLM is ready!"
        break
    fi
    sleep 10
    ELAPSED=$((ELAPSED + 10))
    echo "Still waiting... ($ELAPSED seconds)"
done

if [ $ELAPSED -ge $MAX_WAIT ]; then
    echo "ERROR: vLLM failed to start within timeout"
    exit 1
fi

# Step 5: Register with Network Node
echo "[5/5] Registering with Network Node..."
sleep 5
bash /data/gonka-scripts/register_with_network.sh

echo ""
echo "========================================="
echo "✓ AUTO-DEPLOYMENT COMPLETE!"
echo "========================================="
echo "Configuration: TP=$TP_VALUE (Winner: $BEST_THROUGHPUT tok/s)"
echo "Production logs: tail -f /data/logs/production_auto.log"
echo "Screen session: screen -r mlnode-prod"
echo "========================================="	
